### ISSUE TITLE
Allow configurable email subject prefix

### ISSUE THREAD

**Issue by fanis** [DownloadTicketService/dl#49]
I just started testing this for internal purposes and one of the first things I had to do was to customize the email subject prefix from `"[dl]"` to `"[$companyName]"` in `htdocs/include/msg.php`

I believe it would be useful to expose this as a `config.php` variable, and would gladly provide a pull request if you believe it will be useful to the project.

**Comment by wavexx** [comment]
On Tue, Aug 08 2017, Fanis Hatzidakis wrote:
> I believe it would be useful to expose this as a `config.php`
> variable, and would gladly provide a pull request if you believe it
> will be useful to the project.

This is something I was thinking about and then forgot.
I'll put this in for 0.18.

**Comment by fanis** [comment]
I used this opportunity to set up my first pull request here on github, I'll post it and leave it up to you.

**Comment by wavexx** [comment]
I reworked it to preserve existing values and strip the prefix from the translation text, but it's in.
