### ISSUE TITLE
Canceled upload

### ISSUE THREAD

**Issue by slicki** [DownloadTicketService/dl#54]
Hi,

so I tried uploading several files and while the progress bar did it's thing, I changed the tab to "active tickets". After the estimated time, the files were not uploaded. Does changing to another tab or closing the browser interrupt the upload? And if yes, how is that avoidable?

Best regards,
slicki

**Comment by wavexx** [comment]
On Wed, Aug 16 2017, slicki wrote:
> Hi,
>
> so I tried uploading several files and while the progress bar did it's
> thing, I changed the tab to "active tickets". After the estimated
> time, the files were not uploaded. Does changing to another tab or
> closing the browser interrupt the upload? And if yes, how is that
> avoidable?

Yes, switching to another URL while the upload is running will cancel
the upload.

I could disable all links in the page when the upload starts, but it
seems overkill to me.

**Comment by slicki** [comment]
Thanks for the quick reply!

> Yes, switching to another URL while the upload is running will cancel the upload.

Ah, ok. That explains it. 

> I could disable all links in the page when the upload starts, but it seems overkill to me.

Totally agree. But isn't there a way to just run it as a background process? Otherwise, if I upload e.g. 3GB, the tab needs to be open until the upload finished. And that could take up to 15 min.

**Comment by wavexx** [comment]
On Wed, Aug 16 2017, slicki wrote:
> Totally agree. But isn't there a way to just run it as a background
> process? Otherwise, if I upload e.g. 3GB, the tab needs to be open
> until the upload finished. And that could take up to 15 min.

AFAIK, even with a ServiceWorker you have limitations that would prevent
such a long transfer to finish once the page is effectively closed.

This is also not going to change with resumable uploads, as a page with
the current status needs to remain visible for the whole length of the
upload.

If you do uploads often, use a native client (dl-cli if you are on
*nix). You can just background the job as any other. It's much more
convenient.

**Comment by slicki** [comment]
>AFAIK, even with a ServiceWorker you have limitations that would prevent such a long transfer to finish once the page is effectively closed. This is also not going to change with resumable uploads, as a page with the current status needs to remain visible for the whole length of the upload.

Welp, that's a bummer. But kinda what I expected :P 

> If you do uploads often, use a native client (dl-cli if you are on *nix). You can just background the job as any other. It's much more convenient.

Think I'm going to try out the client.
Thanks again!
