### ISSUE TITLE
DB migration error on MySQL

### ISSUE THREAD

**Issue by dani** [DownloadTicketService/dl#57]
On MySQL, grant is a reserved word, so the table must be quoted. Actually, a migration to 0.18 fails with:

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual
 that corresponds to your MySQL server version for the right syntax to use near ''grant' DROP downloads' at line 1' in /usr/share/dl/include/scripts/dbupgrade.php:76

will send a PR ASAP

**Comment by wavexx** [comment]
We should probably do some automated tests for DB upgrade and basic functionality.
I cannot test directly on mysql.

FIY, this probably happened even before, but I enabled SQL exceptions recently to trap this kind of silent failures when I noticed your previous PR didn't actually work on Postgres or sqlite3.

**Comment by dani** [comment]
Yes, this same error probably happenned silently before (but I started to use DL on v 0.12, so I haven't tested previous upgrades steps). Cross engine compat is a real pain. There're probably frameworks which can help with this, but that's not my area of expertise...
