### ISSUE TITLE
Issue with sending download-link to several email-addresses

### ISSUE THREAD

**Issue by slicki** [DownloadTicketService/dl#64]
Hi,

I just noticed that if I create a new ticket and type in e.g. three email-addresses in the field "send link to email", then the link gets "multiplied" in the mail, depending in which order I wrote the addresses.

For example: 

send link to e-mail
test1@test.com, test2@test.com, test3@test.com

test1 gets the link once. So far so good. 
test2 however, gets the link twice in the mail.
test3 gets it three times.

Looks like the problem comes from the `onTicketCreate - foreach` in the `hook.php`. Found a workaround for this problem, just wanted to let you know that this issue exists.

Best regards,
slicki

**Comment by wavexx** [comment]
Thanks for the report. I noticed the issue was also present for grant notifications, and should now both be fixed.
